config/routes.rb
Rails.application.routes.draw do
  root to: "trends#index"
  resources :trends do
    resources :comments
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :trend, dependent: :destroy
end

app/models/trend.rb
class Trend < ApplicationRecord
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @trend = Trend.find(params[:trend_id])
    @comment = @trend.comments.new
  end

  def create
    @trend = Trend.find(params[:trend_id])
    @comment = @trend.comments.create(comment_params)
    redirect_to trend_path(@trend)
  end

  # def destroy
  #   @trend = Trend.find(params[:trend_id])
  #   @comment = Comment.find(:comment_id)
  #   @comment.destroy
  #   redirect_to trend_path(@trend)
  # end

  private
  def comment_params
    params.require(:comment).permit(:author, :body, :additional_link)
  end
end

app/controllers/trends_controller.rb
class TrendsController < ApplicationController
  def index
    @trends = Trend.all
  end

  def new
    @trend = Trend.new
  end

  def create
    @trend = Trend.create(trend_params)
    redirect_to trend_path(@trend)
  end

  def show
    @trend = Trend.find(params[:id])
    @comments = @trend.comments.all
  end

  def edit
    @trend = Trend.find(params[:id])
  end

  def updated
    @trend = Trend.find(params[:id])
    @trend.update(trend_params)
    redirect_to trend_path(@trend)
  end

  def destroy
    @trend = Trend.find(params[:id])
    @trend.destroy
    redirect_to trends_path()
  end

  private
  def trend_params
    params.require(:trend).permit(:title, :description, :photo_url, :ref_link)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/new.html.erb
<%= link_to "Back", :back %>

<h1> Post New Comment for <%= @trend.title %> </h1>

<%= form_for [@trend, @comment] do |f| %>

  <p>
     <%= f.label :author %><br>
     <%= f.text_field :author %>
  </p>
  <p>
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.label :additional_link %><br>
    <%= f.text_area :additional_link %>
  </p>

  <%= f.submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cleanchomps</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/trends/edit.html.erb
<%= link_to "Back", :back %>

<h1> Edit <%= @trend.title %> </h1>

<%= form_for @trend do |f| %>

  <p>
     <%= f.label :title %><br>
     <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </p>
  <p>
    <%= f.label :photo_url %><br>
    <%= f.text_area :photo_url %>
  </p>
  <p>
    <%= f.label :ref_link %><br>
    <%= f.text_area :ref_link %>
  </p>

  <%= f.submit %>
<% end %>

<%= form_for @trend, url: "/trends/#{@trend.id}", method: :delete do |f| %>
  <% f.submit "Delete Trend", class: "btn-delete" %>
<% end %>

app/views/trends/index.html.erb
<h1> Trends </h1>
<h3><%= link_to "Post New Trend", new_trend_path %></h3>


<% @trends.each do |trend| %>
  <a href="/trends/<%= trend.id%>">
    <h2> <%= trend.title %> </h2>
    <img src='<%= trend.photo_url %>' alt="<%= trend.title %>'s image" />
  </a>
<%end%>

app/views/trends/new.html.erb
<%= link_to "Back", :back %>

<h1> Post New Trend </h1>

<%= form_for @trend do |f| %>

  <p>
     <%= f.label :title %><br>
     <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </p>
  <p>
    <%= f.label :photo_url %><br>
    <%= f.text_area :photo_url %>
  </p>
  <p>
    <%= f.label :ref_link %><br>
    <%= f.text_area :ref_link %>
  </p>

  <%= f.submit %>
<% end %>

app/views/trends/show.html.erb
<h3><%= link_to 'Back', :back %></h3>
<h1><%= @trend.title%> <span>(<%= link_to "Edit", edit_trend_path(@trend) %>)</span></h1>
<h6>Created: <%= @trend.created_at.to_formatted_s(:long) %></h6>
<img src='<%= @trend.photo_url %>' alt="<%= @trend.title %>" />
<h4> <%= @trend.description %> <h4>
<a href='<%= @trend.ref_link %>' target="_blank"> Find Out More </a>

<br/>
<h2> Comments (<%= link_to "+", new_trend_comment_path(@trend) %>)</h2>
<% @comments.each do |comment| %>
  <p><%= comment.body %></p>
  <h4> - <%= comment.author %></h4>
  <h6>Updated: <%= comment.updated_at.to_formatted_s(:long) %> |
    <%# form_for [@trend, comment], url: "/trends/#{@trend.id}/comments/#{comment.id}", method: :delete do |f| %>
      <%# f.submit "Delete Comment", class: "btn-delete" %>
      <%#end%>
  </h6>
  <hr/>
<%end%>